# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        #un admin herite des droits d'auteur et DE moderateur 
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
        #LE SUPER ADMIN ENGLOBE LE ROLE_ADMIN ET DUCOUP HERITE DU ROLE AUTEUR ET MODERATEUR
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        #on cree un pare-feu uniquement pour le formulaire
        main_login:
            # cette expression reguliere permet de prendre /login (mais pas login_check!)
            pattern:    ^/login$
            anonymous:  true # On autorise alors les anonymes sur ce pare-feu
        main:
            pattern:    ^/
            anonymous:  true
            provider:  in_memory
            form_login:
                login_path: /login
                check_path: /login_check
                
            logout:
                path:   logout
                target: /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }